name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
  e2e-tests:
    uses: ./.github/workflows/e2e-tests.yml
    needs: [unit-tests]